// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoDsin;

#nullable disable

namespace ProjetoDsin.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20250522234445_SegundaMigracao")]
    partial class SegundaMigracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ProjetoDsin.Models.Anexos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DadosVeiculoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Evidencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdDadosVeiculo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DadosVeiculoId");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("ProjetoDsin.Models.DadosProprietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DadosVeiculoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdDadosVeiculo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DadosVeiculoId");

                    b.ToTable("DadosProprietarios");
                });

            modelBuilder.Entity("ProjetoDsin.Models.DadosVeiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ano")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DadosVeiculos");
                });

            modelBuilder.Entity("ProjetoDsin.Models.DetalhesInfracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoInfracao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DadosVeiculoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gravidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hota")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdDadosVeiculo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocaInfracao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PontosCnh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoInfracao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DadosVeiculoId");

                    b.ToTable("DetalhesInfracaos");
                });

            modelBuilder.Entity("ProjetoDsin.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoAgente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoOrg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProjetoDsin.Models.Anexos", b =>
                {
                    b.HasOne("ProjetoDsin.Models.DadosVeiculo", "DadosVeiculo")
                        .WithMany()
                        .HasForeignKey("DadosVeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DadosVeiculo");
                });

            modelBuilder.Entity("ProjetoDsin.Models.DadosProprietario", b =>
                {
                    b.HasOne("ProjetoDsin.Models.DadosVeiculo", "DadosVeiculo")
                        .WithMany()
                        .HasForeignKey("DadosVeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DadosVeiculo");
                });

            modelBuilder.Entity("ProjetoDsin.Models.DadosVeiculo", b =>
                {
                    b.HasOne("ProjetoDsin.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoDsin.Models.DetalhesInfracao", b =>
                {
                    b.HasOne("ProjetoDsin.Models.DadosVeiculo", "DadosVeiculo")
                        .WithMany()
                        .HasForeignKey("DadosVeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DadosVeiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
